apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps- 
spec:
  entrypoint: main
  templates:
  - name: delay
    suspend:
      duration: "10s"
  - name: big-delay
    suspend:
      duration: "30s"
  - name: gen-random-int
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        i = random.randint(1, 100)
        print(i)
  - name: main
    steps:
    - - name: step1
        template: delay
    - - name: step2a
        template: big-delay
      - name: step2b
        template: gen-random-int
    - - name: final
        template: delay
